@startuml name package-Diagram
  left to right direction

  skinparam linetype ortho
  skinparam packageStyle rectangle
  skinparam nodesep 50
  skinparam ranksep 80

package "LocationSystem" {
    package "Frontend" {
        package "UI" {
        class HomePage
        class CadastroPage
        class PedidoPage
        }

        package "Controllers" {      
        class UsuarioController
        class AutomovelController
        class PedidoController
        class ContratoController  
        }
    }

  package "Backend" {
    package "Services" {
      class UsuarioService
      class AutomovelService
      class PedidoService
      class ContratoService
    }

    package "Repositories" {
      class UsuarioRepository
      class AutomovelRepository
      class PedidoRepository
      class ContratoRepository
    }

    package "Models" {
      class Automovel
      class Pedido
      class Cliente
      class Contrato
      class Agente
      class Empresa
      class Banco
    }
  }

    package "Database" {
    class MySQLDatabase
    class AutomovelTable
    class PedidoTable
    class ContratoTable
    class ClienteTable
    class AgenteTable
    class EmpresaTable   
    class BancoTable
  }
}

' Relacionamentos (forçados para a parte inferior)
Frontend.Controllers -- Backend.Services
Backend.Services -- Backend.Repositories
Backend.Repositories - Database.MySQLDatabase
Backend.Repositories ..> Backend.Models

@enduml

