@startuml
left to right direction

package "SistemaLocacao" {


  package "Frontend" {
    package "UI" {
      package HomePage{}
      package SearchPage{}
      package UpdatePage{}
      package DeletePage{}
      package UserlistPage{}
      package PedidoPage{}
      package LogoutPage{}
    }

  }

  package "Backend" {

    package "Services" {
      package Agente{}
      package Cliente{}
      package Contrato{}
      package Pedido{}
      package Usuario{}
    }

    package "Controllers" {
      package PedidoController{}
      package LoginController{}
      package ClienteController{}
      package AgenteController{}  
    }

    package "Repositories" {
      package PedidoRepository{}
      package ClienteRepository{}
      package UsuarioRepository{}
      package AutomovelRepository{}
      package AgenteRepository{}
    }

    package "Models" {
      package Pedido{}
      package Contrato{}
      package Cliente{}
      package Agente{}
      package Automovel{}
      package EntidadeEmpregadora{}
      package Usuario{}
      package Endereco{}
    }
  }

}

' Relacionamentos
Backend.Controllers --> Backend.Services
Backend.Services -- Backend.Repositories
Backend.Repositories --> Backend.Models


@enduml