@startuml
node ComputadorPessoal { 
[Navegador]
}

node AplicacaoWeb {
}

ComputadorPessoal  -- AplicacaoWeb : HTTP
AplicacaoWeb -- ServidorAplicacao : HTTP

node ServidorAplicacao {
[AutenticacaoUsuario]
[GestaoPedidosAluguel]
[RegistroAutomovel]
[AvaliacaoPedidos]
[GestaoContrato]
}

[AutenticacaoUsuario] ..> [GestaoPedidosAluguel]
[AutenticacaoUsuario] ..> [RegistroAutomovel]
[GestaoPedidosAluguel] ..> [AvaliacaoPedidos]
[AvaliacaoPedidos] ..> [GestaoContrato]

node BancoDeDados {
[SGBD]
}

ServidorAplicacao -- BancoDeDados : HTTP
@enduml