@startuml
actor Usuário
actor Agente 
actor Cliente
 
rectangle SistemaAluguelCarros{
    Usuário -- (Realizar login)
    Usuário -- (Realizar cadastro)
    Usuário -- (Modificar pedido)
    Usuário -- (Consultar pedido)

    Cliente -- (Criar pedido)
    Cliente -- (Cancelar pedido)

    Agente -- (Avaliar pedido)
    
    (Avaliar pedido) .> (Dar parecer positivo) : <<extends>>
    (Avaliar pedido) .> (Dar parecer negativo) : <<extends>>
    (Dar parecer positivo) .> (Executar Contrato) : <<include>>
    
}
Cliente -|> Usuário
Agente -|> Usuário
@enduml